### ISSUE TITLE
0.4.1 (1.18.2) support?

### ISSUE THREAD

**Issue by DBTDerpbox** [wifi-left/Sodium-Fix-mod#1]
There are multiple people having issues with the crash in a server I run, but the server is made for 1.18.2, are you up for making a 1.18.2 version?

I can't recreate the issue on my own instance, so i'm unable to test if it already works on older versions

**Comment by wifi-left** [comment]
Hi, have they tried this mod already?
If it's convenient, ask them to provide the game log at the time of the crash.
If this version is not compatible on 1.18, I will try to support 1.18.
Thanks.

**Comment by wifi-left** [comment]
Resolved in https://github.com/wifi-left/Sodium-Fix-mod/commit/d0dc9b6bb554b6283807307df7faacc7f782a463 and https://github.com/wifi-left/Sodium-Fix-mod/commit/4234c0d1c8b17b47b853677e9715ac89c19e94cf
Please try the new version (1.0.1)
