### ISSUE TITLE
modpack permission

### ISSUE THREAD

**Issue by OrdinaryCloverOC** [wifi-left/Sodium-Fix-mod#3]
(sorry i didn't see a discord anywhere) your mod doesn't appear to be open source, and i'd like to include it in a mpl v2 modpack. do i have permission to include it?

**Comment by wifi-left** [comment]
The codes are here in the repos:
https://github.com/wifi-left/Sodium-Fix-mod/tree/master/src/main
Feel free to use it.
But pleases warn that the mod may be outdated in the newer version.
After MC version 1.19.2, Sodium has officially solved this problem, and this mod is no longer needed.
