### ISSUE TITLE
i run sodium and i want to join my fabric server and i join and my game say saving world and crash pls help

### ISSUE THREAD

**Issue by iKARY19** [wifi-left/Sodium-Fix-mod#4]

**Comment by wifi-left** [comment]
please provide the logs.
Otherwise I can't help you.

**Comment by wifi-left** [comment]
It's not the same problem of that issue.
It seemed to be **Flywheel's** problem.

**Comment by wifi-left** [comment]
You can try https://modrinth.com/mod/iris-flw-compat
